export interface RegisterMeta {
  label: string
  unit?: string
}

export interface FieldMeta {
  label: string
  unit?: string
  min?: number
  max?: number
}

export const REGISTER_META: Record<string, RegisterMeta> = {
  ManufacturerAccess:          { label: "Manufacturer Access" },
  RemainingCapacityAlarm:      { label: "Remaining Capacity Alarm", unit: "mAh" },
  RemainingTimeAlarm:          { label: "Remaining Time Alarm",     unit: "min" },
  BatteryMode:                 { label: "Battery Mode" },
  AtRate:                      { label: "At Rate",                  unit: "mA" },
  AtRateTimeToFull:            { label: "At Rate Time to Full",     unit: "min" },
  AtRateTimeToEmpty:           { label: "At Rate Time to Empty",    unit: "min" },
  AtRateOK:                    { label: "At Rate OK" },
  Temperature:                 { label: "Temperature",             unit: "0.1 K" },
  Voltage:                     { label: "Pack Voltage",            unit: "mV" },
  Current:                     { label: "Pack Current",            unit: "mA" },
  AverageCurrent:              { label: "Average Current",         unit: "mA" },
  MaxError:                    { label: "Max Error",               unit: "%" },
  RelativeStateOfCharge:       { label: "State of Charge",         unit: "%" },
  AbsoluteStateOfCharge:       { label: "Absolute SoC",            unit: "%" },
  RemainingCapacity:           { label: "Remaining Capacity",      unit: "mAh" },
  FullChargeCapacity:          { label: "Full Charge Capacity",    unit: "mAh" },
  RunTimeToEmpty:              { label: "Run Time to Empty",       unit: "min" },
  AverageTimeToEmpty:          { label: "Avg Time to Empty",       unit: "min" },
  AverageTimeToFull:           { label: "Avg Time to Full",        unit: "min" },
  ChargingCurrent:             { label: "Charging Current",        unit: "mA" },
  ChargingVoltage:             { label: "Charging Voltage",        unit: "mV" },
  BatteryStatus:               { label: "Battery Status" },
  CycleCount:                  { label: "Cycle Count" },
  DesignCapacity:              { label: "Design Capacity",         unit: "mAh" },
  DesignVoltage:               { label: "Design Voltage",          unit: "mV" },
  SpecificationInfo:           { label: "Specification Info" },
  ManufactureDate:             { label: "Manufacture Date" },
  SerialNumber:                { label: "Serial Number" },
  ManufacturerName:            { label: "Manufacturer Name" },
  DeviceName:                  { label: "Device Name" },
  DeviceChemistry:             { label: "Device Chemistry" },
  ManufacturerData:            { label: "Manufacturer Data" },
  Configuration:               { label: "Configuration" },
  MainControl:                 { label: "Main Control" },
  FETState:                    { label: "FET State" },
  VoltageProtectionControl:    { label: "Voltage Protection" },
  CurrentProtectionControl:    { label: "Current Protection" },
  TemperatureProtectionControl:{ label: "Temperature Protection" },
  OCV:                         { label: "OCV Table" },
  Impedance:                   { label: "Impedance Table" },
  CellVoltage:                 { label: "Cell Voltages",           unit: "mV" },
  CellTemperature:             { label: "Cell Temperatures",       unit: "0.1°C" },
  FETStatus:                   { label: "FET Status" },
  CellSoC:                     { label: "Cell State of Charge",    unit: "%" },
  CellSoH:                     { label: "Cell State of Health",    unit: "%" },
  CellRemainingCapacity:       { label: "Cell Remaining Capacity", unit: "mAh" },
  CellSelfDischarge:           { label: "Cell Self-Discharge",     unit: "mAh/month" },
  FaultSnapshot:               { label: "Fault Snapshot" },
  FaultHistory:                { label: "Fault History" },
  ProtectionEventCounters:     { label: "Protection Event Counters" },
  CurrentSensorCalibration:    { label: "Current Sensor Calibration" },
  VoltageCalibration:          { label: "Voltage Calibration" },
  TemperatureCalibration:      { label: "Temperature Calibration" },
  CellBalancingEnergy:         { label: "Cell Balancing Energy",   unit: "mWh" },
  CellBalancingTime:           { label: "Cell Balancing Time",     unit: "min" },
  CellDeepestDischarge:        { label: "Cell Deepest Discharge",  unit: "%" },
  CellMaxTemperature:          { label: "Cell Max Temperature",    unit: "°C" },
  CellQmax:                    { label: "Cell Qmax",               unit: "mAh" },
  FirmwareVersion:             { label: "Firmware Version" },
  HardwareVersion:             { label: "Hardware Version" },
  BoardSerialNumber:           { label: "Board Serial Number" },
  LastCommunicationTimestamp:  { label: "Last Communication" },
  UptimeCounter:               { label: "Uptime",                  unit: "s" },
  BalancingStatus:             { label: "Balancing Status" },
  BalancingControl:            { label: "Balancing Control" },
}

export const FIELD_META: Record<string, FieldMeta> = {
  "BatteryStatus.ERROR_CODE":                            { label: "Error Code" },
  "VoltageProtectionControl.slow_uvp_threshold_mv":      { label: "Slow UVP Threshold",    unit: "mV", min: 0, max: 65535 },
  "VoltageProtectionControl.slow_uvp_detection_time_ms": { label: "Slow UVP Time",         unit: "ms", min: 0, max: 65535 },
  "VoltageProtectionControl.fast_uvp_threshold_mv":      { label: "Fast UVP Threshold",    unit: "mV", min: 0, max: 65535 },
  "VoltageProtectionControl.fast_uvp_detection_time_ms": { label: "Fast UVP Time",         unit: "ms", min: 0, max: 65535 },
  "VoltageProtectionControl.slow_ovp_threshold_mv":      { label: "Slow OVP Threshold",    unit: "mV", min: 0, max: 65535 },
  "VoltageProtectionControl.slow_ovp_detection_time_ms": { label: "Slow OVP Time",         unit: "ms", min: 0, max: 65535 },
  "VoltageProtectionControl.fast_ovp_threshold_mv":      { label: "Fast OVP Threshold",    unit: "mV", min: 0, max: 65535 },
  "VoltageProtectionControl.fast_ovp_detection_time_ms": { label: "Fast OVP Time",         unit: "ms", min: 0, max: 65535 },
  "CurrentProtectionControl.charge_ocp_threshold_ma":    { label: "Charge OCP Threshold",  unit: "mA", min: 0, max: 65535 },
  "CurrentProtectionControl.charge_ocp_detection_time_ms": { label: "Charge OCP Time",     unit: "ms", min: 0, max: 65535 },
  "CurrentProtectionControl.slow_discharge_ocp_threshold_ma": { label: "Slow Disch OCP",   unit: "mA", min: 0, max: 65535 },
  "CurrentProtectionControl.slow_discharge_ocp_time_ms": { label: "Slow Disch OCP Time",   unit: "ms", min: 0, max: 65535 },
  "CurrentProtectionControl.fast_discharge_ocp_threshold_ma": { label: "Fast Disch OCP",   unit: "mA", min: 0, max: 65535 },
  "CurrentProtectionControl.fast_discharge_ocp_time_ms": { label: "Fast Disch OCP Time",   unit: "ms", min: 0, max: 65535 },
  "TemperatureProtectionControl.otp_threshold_c":        { label: "OTP Threshold",         unit: "°C", min: 0, max: 100 },
  "TemperatureProtectionControl.otp_detection_time_ms":  { label: "OTP Detection Time",    unit: "ms", min: 0, max: 65535 },
  "Configuration.CELL_COUNT":                            { label: "Cell Count",             min: 2, max: 7 },
  "CurrentSensorCalibration.offset":                     { label: "Current Offset" },
  "CurrentSensorCalibration.gain":                       { label: "Current Gain" },
}