import type { RegisterValue } from "@/bindings";

export interface RegisterMeta {
    label: string;
    unit?: string;
}

export interface FieldMeta {
    label: string;
    unit?: string;
    min?: number;
    max?: number;
}

export const REGISTER_META: Record<string, RegisterMeta> = {
    ManufacturerAccess: { label: "Manufacturer Access" },
    RemainingCapacityAlarm: { label: "Remaining Capacity Alarm", unit: "mAh" },
    RemainingTimeAlarm: { label: "Remaining Time Alarm", unit: "min" },
    BatteryMode: { label: "Battery Mode" },
    AtRate: { label: "At Rate", unit: "mA" },
    AtRateTimeToFull: { label: "At Rate Time to Full", unit: "min" },
    AtRateTimeToEmpty: { label: "At Rate Time to Empty", unit: "min" },
    AtRateOK: { label: "At Rate OK" },
    Temperature: { label: "Temperature", unit: "0.1 K" },
    Voltage: { label: "Pack Voltage", unit: "mV" },
    Current: { label: "Pack Current", unit: "mA" },
    AverageCurrent: { label: "Average Current", unit: "mA" },
    MaxError: { label: "Max Error", unit: "%" },
    RelativeStateOfCharge: { label: "State of Charge", unit: "%" },
    AbsoluteStateOfCharge: { label: "Absolute SoC", unit: "%" },
    RemainingCapacity: { label: "Remaining Capacity", unit: "mAh" },
    FullChargeCapacity: { label: "Full Charge Capacity", unit: "mAh" },
    RunTimeToEmpty: { label: "Run Time to Empty", unit: "min" },
    AverageTimeToEmpty: { label: "Avg Time to Empty", unit: "min" },
    AverageTimeToFull: { label: "Avg Time to Full", unit: "min" },
    ChargingCurrent: { label: "Charging Current", unit: "mA" },
    ChargingVoltage: { label: "Charging Voltage", unit: "mV" },
    BatteryStatus: { label: "Battery Status" },
    CycleCount: { label: "Cycle Count" },
    DesignCapacity: { label: "Design Capacity", unit: "mAh" },
    DesignVoltage: { label: "Design Voltage", unit: "mV" },
    SpecificationInfo: { label: "Specification Info" },
    ManufactureDate: { label: "Manufacture Date" },
    SerialNumber: { label: "Serial Number" },
    ManufacturerName: { label: "Manufacturer Name" },
    DeviceName: { label: "Device Name" },
    DeviceChemistry: { label: "Device Chemistry" },
    ManufacturerData: { label: "Manufacturer Data" },
    Configuration: { label: "Configuration" },
    MainControl: { label: "Main Control" },
    FETState: { label: "FET State" },
    VoltageProtectionControl: { label: "Voltage Protection" },
    CurrentProtectionControl: { label: "Current Protection" },
    TemperatureProtectionControl: { label: "Temperature Protection" },
    OCV: { label: "OCV Table" },
    Impedance: { label: "Impedance Table" },
    CellVoltage: { label: "Cell Voltages", unit: "mV" },
    CellTemperature: { label: "Cell Temperatures", unit: "0.1°C" },
    FETStatus: { label: "FET Status" },
    CellSoC: { label: "Cell State of Charge", unit: "%" },
    CellSoH: { label: "Cell State of Health", unit: "%" },
    CellRemainingCapacity: { label: "Cell Remaining Capacity", unit: "mAh" },
    CellSelfDischarge: { label: "Cell Self-Discharge", unit: "mAh/month" },
    FaultSnapshot: { label: "Fault Snapshot" },
    FaultHistory: { label: "Fault History" },
    ProtectionEventCounters: { label: "Protection Event Counters" },
    CurrentSensorCalibration: { label: "Current Sensor Calibration" },
    VoltageCalibration: { label: "Voltage Calibration" },
    TemperatureCalibration: { label: "Temperature Calibration" },
    CellBalancingEnergy: { label: "Cell Balancing Energy", unit: "mWh" },
    CellBalancingTime: { label: "Cell Balancing Time", unit: "min" },
    CellDeepestDischarge: { label: "Cell Deepest Discharge", unit: "%" },
    CellMaxTemperature: { label: "Cell Max Temperature", unit: "°C" },
    CellQmax: { label: "Cell Qmax", unit: "mAh" },
    FirmwareVersion: { label: "Firmware Version" },
    HardwareVersion: { label: "Hardware Version" },
    BoardSerialNumber: { label: "Board Serial Number" },
    LastCommunicationTimestamp: { label: "Last Communication" },
    UptimeCounter: { label: "Uptime", unit: "s" },
    BalancingStatus: { label: "Balancing Status" },
    BalancingControl: { label: "Balancing Control" },
};

export const FIELD_META: Record<string, FieldMeta> = {
    "BatteryStatus.ERROR_CODE": { label: "Error Code" },
    "VoltageProtectionControl.slow_uvp_threshold_mv": {
        label: "Slow UVP Threshold",
        unit: "mV",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.slow_uvp_detection_time_ms": {
        label: "Slow UVP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.fast_uvp_threshold_mv": {
        label: "Fast UVP Threshold",
        unit: "mV",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.fast_uvp_detection_time_ms": {
        label: "Fast UVP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.slow_ovp_threshold_mv": {
        label: "Slow OVP Threshold",
        unit: "mV",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.slow_ovp_detection_time_ms": {
        label: "Slow OVP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.fast_ovp_threshold_mv": {
        label: "Fast OVP Threshold",
        unit: "mV",
        min: 0,
        max: 65535,
    },
    "VoltageProtectionControl.fast_ovp_detection_time_ms": {
        label: "Fast OVP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "CurrentProtectionControl.charge_ocp_threshold_ma": {
        label: "Charge OCP Threshold",
        unit: "mA",
        min: 0,
        max: 65535,
    },
    "CurrentProtectionControl.charge_ocp_detection_time_ms": {
        label: "Charge OCP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "CurrentProtectionControl.slow_discharge_ocp_threshold_ma": {
        label: "Slow Disch OCP",
        unit: "mA",
        min: 0,
        max: 65535,
    },
    "CurrentProtectionControl.slow_discharge_ocp_time_ms": {
        label: "Slow Disch OCP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "CurrentProtectionControl.fast_discharge_ocp_threshold_ma": {
        label: "Fast Disch OCP",
        unit: "mA",
        min: 0,
        max: 65535,
    },
    "CurrentProtectionControl.fast_discharge_ocp_time_ms": {
        label: "Fast Disch OCP Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "TemperatureProtectionControl.otp_threshold_c": {
        label: "OTP Threshold",
        unit: "°C",
        min: 0,
        max: 100,
    },
    "TemperatureProtectionControl.otp_detection_time_ms": {
        label: "OTP Detection Time",
        unit: "ms",
        min: 0,
        max: 65535,
    },
    "Configuration.CELL_COUNT": { label: "Cell Count", min: 2, max: 7 },
    "CurrentSensorCalibration.offset": { label: "Current Offset" },
    "CurrentSensorCalibration.gain": { label: "Current Gain" },
};

/** Register base addresses, mirroring src-tauri/src/register_map.rs */
export const REGISTER_ADDR: Record<string, number> = {
    ManufacturerAccess: 0x00,
    RemainingCapacityAlarm: 0x01,
    RemainingTimeAlarm: 0x02,
    BatteryMode: 0x03,
    AtRate: 0x04,
    AtRateTimeToFull: 0x05,
    AtRateTimeToEmpty: 0x06,
    AtRateOK: 0x07,
    Temperature: 0x08,
    Voltage: 0x09,
    Current: 0x0a,
    AverageCurrent: 0x0b,
    MaxError: 0x0c,
    RelativeStateOfCharge: 0x0d,
    AbsoluteStateOfCharge: 0x0e,
    RemainingCapacity: 0x0f,
    FullChargeCapacity: 0x10,
    RunTimeToEmpty: 0x11,
    AverageTimeToEmpty: 0x12,
    AverageTimeToFull: 0x13,
    ChargingCurrent: 0x14,
    ChargingVoltage: 0x15,
    BatteryStatus: 0x16,
    CycleCount: 0x17,
    DesignCapacity: 0x18,
    DesignVoltage: 0x19,
    SpecificationInfo: 0x1a,
    ManufactureDate: 0x1b,
    SerialNumber: 0x1c,
    ManufacturerName: 0x20,
    DeviceName: 0x21,
    DeviceChemistry: 0x22,
    ManufacturerData: 0x23,
    Configuration: 0x40,
    MainControl: 0x41,
    FETState: 0x42,
    VoltageProtectionControl: 0x43,
    CurrentProtectionControl: 0x44,
    TemperatureProtectionControl: 0x45,
    OCV: 0x46,
    Impedance: 0x47,
    CellVoltage: 0x48,
    CellTemperature: 0x49,
    FETStatus: 0x4a,
    CellSoC: 0x4b,
    CellSoH: 0x4c,
    CellRemainingCapacity: 0x4d,
    CellSelfDischarge: 0x4e,
    FaultSnapshot: 0x4f,
    FaultHistory: 0x50,
    ProtectionEventCounters: 0x51,
    CurrentSensorCalibration: 0x52,
    VoltageCalibration: 0x53,
    TemperatureCalibration: 0x54,
    CellBalancingEnergy: 0x55,
    CellBalancingTime: 0x56,
    CellDeepestDischarge: 0x57,
    CellMaxTemperature: 0x58,
    CellQmax: 0x59,
    FirmwareVersion: 0x5a,
    HardwareVersion: 0x5b,
    BoardSerialNumber: 0x5c,
    LastCommunicationTimestamp: 0x5d,
    UptimeCounter: 0x5e,
    BalancingStatus: 0x5f,
    BalancingControl: 0x60,
};

/** Renders a RegisterValue as 0xXXXX (4 hex digits) */
export function formatRegisterHex(value: RegisterValue): string {
    if ("Word" in value)
        return `0x${value.Word.toString(16).toUpperCase().padStart(4, "0")}`;
    if ("SignedWord" in value)
        return `0x${(value.SignedWord & 0xffff).toString(16).toUpperCase().padStart(4, "0")}`;
    return `[${value.Block.length}B]`;
}
