// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BmsConfig = { version: number, battery_mode: number, at_rate: number, charging_current_ma: number, charging_voltage_mv: number, configuration: number, main_control: number, fet_state: number, balancing_control: number, protection_voltage: Array<number>, protection_current: Array<number>, protection_temperature: Array<number>, calibration_current: Array<number>, calibration_voltage: Array<number>, calibration_temperature: Array<number>, };
