// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Access } from "./Access";
import type { FieldType } from "./FieldType";

export type FieldDef = { name: string, access: Access, field_type: FieldType, };
