// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimitiveType } from "./PrimitiveType";

export type FieldType =
	| { Bit: number }
	| { BitRange: { high: number; low: number } }
	| { ByteField: { byte_offset: number; prim: PrimitiveType } }
	| { PrimitiveArray: { count: number; prim: PrimitiveType } };
