// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BmsData = {
    temperature_dk: number;
    voltage_mv: number;
    current_ma: number;
    average_current_ma: number;
    relative_soc: number;
    absolute_soc: number;
    remaining_capacity: number;
    full_charge_capacity: number;
    run_time_to_empty: number;
    average_time_to_empty: number;
    average_time_to_full: number;
    battery_status: number;
    cycle_count: number;
    cell_voltages_mv: [number, number, number, number, number, number, number];
    cell_temperatures: [number, number, number, number, number, number, number];
    cell_soc: [number, number, number, number, number, number, number];
    fet_status: number;
    balancing_status: number;
    at_rate: number;
    at_rate_time_to_full: number;
    at_rate_time_to_empty: number;
    at_rate_ok: number;
    charging_current_ma: number;
    charging_voltage_mv: number;
    fet_state: number;
    balancing_control: number;
    cell_soh: [number, number, number, number, number, number, number];
    cell_remaining_capacity: [
        number,
        number,
        number,
        number,
        number,
        number,
        number,
    ];
};
