// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Access } from "./Access";
import type { FieldDef } from "./FieldDef";
import type { ValueType } from "./ValueType";

export type RegisterDef = {
    name: string;
    access: Access;
    value_type: ValueType;
    fields: Array<FieldDef>;
};
